### PR TITLE
Modify appgw_probes allowing port-usage from backend HTTP settings

### PR DESCRIPTION
**Pull request by twecker137**
WIthin the azurerm_application_gateway resource it is possible to leave the port value unset, to use the configured value in the backend http setting.
While setting the default port to `443`, this option would get lost. Therefore I suggest changing it to null, even if this leads to a change in the module behavior.

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/application_gateway#pick_host_name_from_backend_http_settings

image

### CODE REVIEW

**Review by Shr3ps — CHANGES_REQUESTED** [review]
Hello,

I disagree with this.

If you/a user wants to set the port to "null" then it should be set explicitly when calling this module and not by modifying the default value.

**Comment by twecker137** [comment]
> Hello,
> 
> I disagree with this.
> 
> If you/a user wants to set the port to "null" then it should be set explicitly when calling this module and not by modifying the default value.

Hello, thank you for your response.
I would agree setting this value would be enough. But in this specific case, if I call this module with `null`-port, terraform would choose the default value instead. Or do I miss something?

For example, module call:
```hcl
module "appgw" {
###
  appgw_probes = [
    {
      ###
      port = null
    }
  ]
}
 

```

Would produce the following:
```hcl
probe {
          + id                                        = (known after apply)
          + interval                                  = 5
          + minimum_servers                           = 0
          + name                                      = "path-name"
          + path                                      = "/path"
          + pick_host_name_from_backend_http_settings = true
          + port                                      = 443
          + protocol                                  = "Http"
          + timeout                                   = 16
          + unhealthy_threshold                       = 3

          + match {
              + status_code = [
                  + "200-399",
                ]
            }
        }

```

**Comment by BzSpi** [comment]
Hello @twecker137 

You shouldn't have this behavior. What Terraform version are you using ?

**Comment by twecker137** [comment]
> Hello @twecker137
> 
> You shouldn't have this behavior. What Terraform version are you using ?

I have been using Terraform version 1.3.1, but I tested it is still an issue with version 1.3.7 and agw module version 7.3.0.
But from my point of view it is default Terraform behaviour. For example the following code:

```hcl
# main.tf
module "test" {
  source = "./modules/test-module"
  object = [{
    port = null
  }] 
  # Can also write: object = [{}]
}

output "module-output" {
  value = module.test.object
}
```

```hcl
# modules/test-module/main.tf
variable "object" {
  type = list(object({
    port = optional(number, 443)
  }))
}

output "object" {
  value = var.object
}
```

Is producing the following:

```shell
Changes to Outputs:
  + module-output = [
      + {
          + port = 443
        },
    ]
```

**Review by BzSpi — APPROVED** [review]

**Review by rossifumax — APPROVED** [review]

**Pull request merged**
